baseURL = 'https://fadiocn.github.io/'
languageCode = 'zh-CN'
title = '发声电台Fadio'

hasCJKLanguage = true


theme = "PaperMod"


[outputs]
  home = ["HTML", "RSS", "JSON"]

[params.label]
    text = "发声电台Fadio"           # 导航栏显示的文字
    icon = "/img/avatar.png"      # 对应 static/img/icon.png，不要加 /static/ 前缀
    iconHeight = 35            # 图标高度，单位默认是 px


enableGitInfo = true
enableRobotsTXT = true
canonifyURLs = true
enableRSS = true
defaultContentLanguage = "zh"

# [author]
#  name = "路发"

[menu]

  [[menu.main]]
    identifier = "home"
    name = "首页"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "posts"
    name = "文章"
    url = "/posts/"
    weight = 2

  [[menu.main]]
    name = "标签"
    url = "/tags/"
    weight = 3

  [[menu.main]]
    identifier = "about"
    name = "关于"
    url = "/about/"
    weight = 4

  [[menu.main]]
    identifier = "search"
    name = "Search"
    url = "/search/"
    weight = 10

  [[menu.main]]
    identifier = "archives"
    name = "归档"
    url = "/archives/"
    weight = 20

  [[menu.main]]
    identifier = "rss"
    name = "RSS"
    url = "/index.xml"
    weight = 99


# PaperMod 核心参数
[params]

  mainSections = ["posts"]
  
  # —— 站点简介（SEO / RSS / 分享摘要）——
  # description = "记录技术、商业与长期思考的个人博客"
  # keywords = ["打工", "财政", "成长", "写作"]
  
  author = "路发"

  # —— 主题外观 ——
  defaultTheme = "auto"      # auto / light / dark
  disableThemeToggle = false

  # —— 文章增强 ——
  ShowReadingTime = true
  ShowWordCount = true
  ShowPostMeta = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowToc = true
  TocOpen = true
  
  ShowSearchKey = true



  # —— 列表页信息 ——
  ShowRssButtonInSectionTermList = true

  ShowFooter = false

  # =================================================
  # 社交账号（PaperMod 官方方式）
  # =================================================
 socialIcons = [
    { name = "email", url = "mailto:ofa_@email.com" },
    { name = "github", url = "https://github.com/fadiocn" },
    { name = "podcast", url = "https://www.xyzfm.link/3a8cr" },
    { name = "rss", url = "index.xml" }
    ]

  

#{ name = "github" ,     url = "https://github.com/fadiocn" }
# { name = "linkedin" ,   url = "https://www.linkedin.com/in/yourname/" }
# { name = "twitter" ,    url = "https://twitter.com/yourname" }

# =====================================================
# RSS 配置（Hugo 默认开启，这里是增强）
# =====================================================


#[params.profileMode]
#  enabled = false
#  title = "路发"
#  subtitle = "我的博客 / 注释"
#  imageUrl = "/img/avatar.png"
#  imageTitle = "头像"
#  imageWidth = 120
#  imageHeight = 120